# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto

  pod 'secp256k1.swift'
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

  target 'CryptoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CryptoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
